### PR TITLE
Added Reflection stuff and nuget package

### PR DESCRIPTION
**Pull request by Ascent691**
Please check the nuget package and make sure I did it right :facepunch:

### CODE REVIEW

**Comment by fluffynuts** [comment]
Hi Matt

This new inclusion is looking interesting. Sorry for taking so long to get around to reviewing it.

I'd like to include it in PeanutButter, and I will, if you can help me out a bit:

The following require some kind of testing:
EventInfoExtensions
FieldInfoExtensions
MethodInfoExtensions
PropertyInfoExtensions

DotCover shows them at 0%.

In addition, from ITypeEnumeratorFilterCriteria:
ValueTypes
Static
AndNot
ConstructedWithParameters
ConstructedWithNoParameters
ConstructedGenericTypes
Classes
Abstract
IsStatic
IsDefined
IsClasses (I'm sure that should be "IsClass"?)

Unlike some of the other cruft in PB (and there's some well difficult-to-the-point-of-fuckit items to test in there, like ServiceShell -- a necessary evil though, methinks), I think these are all quite testable (and can boost the overall coverage of PB) -- indeed, I'm willing to process the pull request and divide the testing between us, as I think these look like useful extensions. 

I'd also really like some examples of usage (I'm sure you have some -- these wouldn't have been borne out of pure boredom, not when MineCraft and Witcher3 still exist) -- again, we can split the work on that -- because I'd like to make a giant hullabaloo about it on my blog, in welcoming you as a contributor. I'm sure JB will be quite forthcoming with a R# license too then (:

Your thoughts?

(again, apologies for my utter lameness; been sick and operated on and just generally lazy).

**Comment by Ascent691** [comment]
No problem Davyd,

Dont stress about dividing the work, I will make sure that the outstanding coverage is addressed and ill also rename that derp with "IsClasses".

With regards to examples of usage, would it be appropriate to include a real world example such as an attribute driven factory class, or would you prefer smaller examples ?

**Comment by fluffynuts** [comment]
I like the sound of your more complex example - showing off why this
library is the kind of thing you'd want to use often but only code once (:

-d

**Comment by Ascent691** [comment]
Ok great, ill get that done sometime in the next day or so and we can go from there!

**Comment by fluffynuts** [comment]
PS:  the example is something I'd like to put up on my blog (with
attribution, or course) , so you can feel free to write it as a tutorial or
however you please. The purpose here is twofold:
To provide a reference for the utilities
To provide an introduction to the library which I can use as part of my
motivation to JetBrains for R# licensing for you. Their open-source
initiative revolves avoid three requirements: open-source code (obviously),
usage information (which nuget shows - you don't have to worry about this
as PB has plenty high stats, largely from our build processes) and a
public-facing website (or blog) which is kept up to date and talks (at
least in part) about the project.

Also, if we can get a blog post up about your work, Chris will like to
tweet about it on behalf of Chillisoft. And you'll be doing better than the
components of PB that I still haven't gotten around to blogging about (:

-d

**Comment by fluffynuts** [comment]
Any news on this front? (:

**Comment by fluffynuts** [comment]
Closing for now. Please PR again when you have the time -- I'd appreciate it!

**Pull request closed without merging**
