### PR TITLE
SimpleHttpServer: Added support for further HTTP methods

### PR DESCRIPTION
**Pull request by less0**
For I needed the `SimpleHttpServer` to support the `PUT` and `PATCH` methods for my tests, I supplied them on my own.

### CODE REVIEW

**Comment by less0** [comment]
Do not merge, yet, there are still some issues, it seems

**Comment by fluffynuts** [comment]
hi @less0 

thanks for the PR!

hopefully I can have a look at this tomorrow morning, merge and release!

I'm so glad this lib is of some use to someone else :D

**Review by fluffynuts — COMMENTED** [review]
I like the move to a generic "handle with body" - what do you think about:
1. Genericising the `HandleGETRequest` name, eg `HandleRequestWithoutBody`
2. removing `HandlePOSTRequest` from the api - I don't think it's actually something that should be available to the code consuming the server and there are no references to it within PB
3. Perhaps making the HandleRequest methods protected, for the same reason as (2)

?

There's nothing wrong with what you've done - you've improved things! It's just made me think about the overall design; this code is about 8 years old!

**Comment by less0** [comment]
@fluffynuts Sounds great. I'll see whether I can commit the changes today.

**Comment by less0** [comment]
@fluffynuts Have a look at it now. Anything alike what you thought of?

**Review by fluffynuts — COMMENTED** [review]
LGTM

**Comment by fluffynuts** [comment]
@less0 just waiting on the test run then I'll pull & release

**Comment by fluffynuts** [comment]
@less0 3.0.11 is out (:

**Comment by less0** [comment]
> @less0 3.0.11 is out (:

Already removed my custom DLLs and pulled the Version from NuGet ;)

**Pull request merged**
